version: '3.8'

services:
  math-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:50051'); channel.channel_ready()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - PYTHONUNBUFFERED=1